In [1]:
import numpy as np
import matplotlib.pyplot as plt

from scipy.fft import fft2, ifft2, fftshift, ifftshift

from classicalfield import FiniteTempGPE as gpe

In [12]:
test_arr = np.array([[0,0,0],[0,1,0],[0,0,0]])

#g = gpe()


In [13]:
N = len(test_arr[0]) * len(test_arr)
L = len(test_arr)
dx = L/np.sqrt(N)

L2 = 300
dx2  = 100


Take $L$ to be the window length (since we are including classical noise outside of the box into the window itself) and $dx$ to be the spacing between grid points. These paramters are defined in the Python script already. We now define the density $n_k$ to be the 3x3 array that contains all zeros except for the center position at (1,1) that instead contains a $1$. Evaluating the expression $\tilde{\psi}_k = L/\Delta x^2 \sqrt{n_k}$ retrieves the wavefunction value in $k$ space expected by scipy's Fourier transform definition. Taking the inverse Fourier transform transforms the function into real space. Integrating over the resultant $|\psi(x)|^2$ yields the number of particles. In this case, the number of particles should be $1$. 

In [14]:
psik_t = L/dx**2 * np.sqrt(test_arr)
print(L/dx**2)
print(L/dx**2 * np.sqrt(test_arr))
print(psik_t)

psix_t = ifft2(psik_t)
print(np.sum(np.abs(psix_t)**2)*dx**2)


3.0
[[0. 0. 0.]
 [0. 3. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 3. 0.]
 [0. 0. 0.]]
1.0


In [5]:
psik_t = L2/dx2**2 * np.sqrt(test_arr)
print(L2/dx2**2)
print(L2/dx2**2 * np.sqrt(test_arr))
print(psik_t)

psix_t = ifft2(psik_t)
print(np.sum(np.abs(psix_t)**2)*dx2**2)

0.03
[[0.   0.   0.  ]
 [0.   0.03 0.  ]
 [0.   0.   0.  ]]
[[0.   0.   0.  ]
 [0.   0.03 0.  ]
 [0.   0.   0.  ]]
0.9999999999999998
